import { course_images } from "./images";

const courses = [
    {
        id: "xMHCZl",
        category: "pottery",
        image: course_images.python_5,
        course_name: "Learn pottery",
        description: "Quack quack quack quack quack quack quack",
        rating_count: 3059,
        rating_star: 4.4,
        students: 18430,
        creator: "Duck",
        updated_date: "9/2015",
        lang: "english",
        actual_price: 84.99,
        discounted_price: 9.99,
        what_you_will_learn: [
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack"
        ],
        content: [
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack"
        ]
    },
    {
        id: "dtfo9e",
        category: "pottery",
        image: course_images.python_5,
        course_name: "Learn pottery 1",
        description: "Quack quack quack quack quack quack quack",
        rating_count: 3059,
        rating_star: 4.4,
        students: 18430,
        creator: "Duck 1",
        updated_date: "9/2015",
        lang: "english",
        actual_price: 84.99,
        discounted_price: 9.99,
        what_you_will_learn: [
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack"
        ],
        content: [
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack"
        ]
    },
    {
        id: "fLroW6",
        category: "pottery",
        image: course_images.python_5,
        course_name: "Learn pottery 2",
        description: "Quack quack quack quack quack quack quack",
        rating_count: 3059,
        rating_star: 4.4,
        students: 18430,
        creator: "Duck 2",
        updated_date: "9/2015",
        lang: "english",
        actual_price: 84.99,
        discounted_price: 9.99,
        what_you_will_learn: [
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack"
        ],
        content: [
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack"
        ]
    },
    {
        id: "VwkN_o",
        category: "pottery",
        image: course_images.python_5,
        course_name: "Learn pottery 3",
        description: "Quack quack quack quack quack quack quack",
        rating_count: 3059,
        rating_star: 4.4,
        students: 18430,
        creator: "Duck 3",
        updated_date: "9/2015",
        lang: "english",
        actual_price: 84.99,
        discounted_price: 9.99,
        what_you_will_learn: [
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack"
        ],
        content: [
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack"
        ]
    },
    {
        id: "xJB-WU",
        category: "pottery",
        image: course_images.python_5,
        course_name: "Learn pottery 4",
        description: "Quack quack quack quack quack quack quack",
        rating_count: 3059,
        rating_star: 4.4,
        students: 18430,
        creator: "Duck 4",
        updated_date: "9/2015",
        lang: "english",
        actual_price: 84.99,
        discounted_price: 9.99,
        what_you_will_learn: [
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack"
        ],
        content: [
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack"
        ]
    },
    {
        id: "qjdYG4",
        category: "oil",
        image: course_images.web_dev_1,
        course_name: "Learn oil 1",
        description: "Quack quack quack quack quack quack quack",
        rating_count: 3059,
        rating_star: 4.4,
        students: 18430,
        creator: "Duck 1",
        updated_date: "9/2015",
        lang: "english",
        actual_price: 84.99,
        discounted_price: 9.99,
        what_you_will_learn: [
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack"
        ],
        content: [
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack"
        ]
    },
    {
        id: "3pm9Ab",
        category: "oil",
        image: course_images.web_dev_1,
        course_name: "Learn oil 2",
        description: "Quack quack quack quack quack quack quack",
        rating_count: 3059,
        rating_star: 4.4,
        students: 18430,
        creator: "Duck 1",
        updated_date: "9/2015",
        lang: "english",
        actual_price: 84.99,
        discounted_price: 9.99,
        what_you_will_learn: [
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack"
        ],
        content: [
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack"
        ]
    },
    {
        id: "RuUs0x",
        category: "oil",
        image: course_images.web_dev_1,
        course_name: "Learn oil 1",
        description: "Quack quack quack quack quack quack quack",
        rating_count: 3059,
        rating_star: 4.4,
        students: 18430,
        creator: "Duck 1",
        updated_date: "9/2015",
        lang: "english",
        actual_price: 84.99,
        discounted_price: 9.99,
        what_you_will_learn: [
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack"
        ],
        content: [
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack"
        ]
    },
    {
        id: "e_0hBc",
        category: "oil",
        image: course_images.web_dev_1,
        course_name: "Learn oil 1",
        description: "Quack quack quack quack quack quack quack",
        rating_count: 3059,
        rating_star: 4.4,
        students: 18430,
        creator: "Duck 1",
        updated_date: "9/2015",
        lang: "english",
        actual_price: 84.99,
        discounted_price: 9.99,
        what_you_will_learn: [
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack"
        ],
        content: [
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack"
        ]
    },
    {
        id: "z9dxdw",
        category: "oil",
        image: course_images.web_dev_1,
        course_name: "Learn oil 1",
        description: "Quack quack quack quack quack quack quack",
        rating_count: 3059,
        rating_star: 4.4,
        students: 18430,
        creator: "Duck 1",
        updated_date: "9/2015",
        lang: "english",
        actual_price: 84.99,
        discounted_price: 9.99,
        what_you_will_learn: [
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack"
        ],
        content: [
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack",
            "Quack quack quack quack quack quack quack"
        ]
    },
    {
        id: "X8Pg1X",
        category: "inlay",
        image: course_images.data_science_1,
        course_name: "Data Science A-Z™: Real-Life Data Science Exercises Included",
        description: "Learn Data Science step by step through real Analytics examples. Data Mining, Modeling, Tableau Visualization and more!",
        rating_count: 32103,
        rating_star: 4.5,
        students: 204985,
        creator: "Kirill Eremenko, Ligency Team",
        updated_date: "9/2022",
        lang: "english",
        actual_price: 77.99,
        discounted_price: 16.99,
        what_you_will_learn: [
            "Successfully perform all steps in a complex Data Science project",
            "Perform Data Mining in Tableau",
            "Apply Ordinary Least Squares method to Create Linear Regressions",
            "Assess the Adjusted R-Squared for all types of models",
            "Create a Multiple Linear Regression (MLR)",
            "Interpret coefficients of an MLR",
            "Use Backward Elimination, Forward Selection, and Bidirectional Elimination methods to create statistical models",
            "Read a Confusion Matrix"
        ],
        content: [
            "What is Data Science?",
            "Part 1: Visualisation",
            "Introduction to Tableau",
            "Advanced Data Mining with Tableau",
            "Stats Refresher",
            "Simple Linear Regression",
            "Model maintenance",
            "SQL Programming for Data Science",
        ]
    },
    {
        id: "9Ui0L1",
        category: "inlay",
        image: course_images.data_science_2,
        course_name: "Machine Learning, Data Science and Deep Learning with Python",
        description: "Complete hands-on machine learning tutorial with data science, Tensorflow, artificial intelligence, and neural networks",
        rating_count: 27687,
        rating_star: 4.5,
        students: 166929,
        creator: "Sundog Education by Frank Kane",
        updated_date: "2/2022",
        lang: ["english", "french"],
        actual_price: 87.99,
        discounted_price: 14.99,
        what_you_will_learn: [
            "Build artificial neural networks with Tensorflow and Keras",
            "Classify images, data, and sentiments using deep learning",
            "Data Visualization with MatPlotLib and Seaborn",
            "Classify data using K-Means clustering, Support Vector Machines (SVM), KNN, Decision Trees, Naive Bayes, and PCA",
            "Build a movie recommender system using item-based and user-based collaborative filtering",
            "Interpret coefficients of an MLR",
        ],
        content: [
            "Statistics and Probability Refresher, and Python Practice",
            "Predictive Models",
            "Machine Learning with Python",
            "Recommender Systems",
            "More Data Mining and Machine Learning Techniques",
            "Dealing with Real-World Data",
            "Apache Spark: Machine Learning on Big Data",
            "Deep Learning and Neural Networks",
        ]
    },
    {
        id: "TKGumi",
        category: "inlay",
        image: course_images.data_science_3,
        course_name: "Data Science: Deep Learning and Neural Networks in Python",
        description: "The MOST in-depth look at neural network theory for machine learning, with both pure Python and Tensorflow code",
        rating_count: 8513,
        rating_star: 4.8,
        students: 50184,
        creator: "Lazy Programmer Inc.",
        updated_date: "8/2022",
        lang: ["english", "Portuguese"],
        actual_price: 90.99,
        discounted_price: 19.99,
        what_you_will_learn: [
            "Learn how Deep Learning REALLY works (not just some diagrams and magical black box code)",
            "Code a neural network from scratch in Python and numpy",
            "Describe different types of neural networks and the different types of problems they are used for",
            "Create a neural network with an output that has K > 2 classes using softmax",
            "Install TensorFlow",
        ],
        content: [
            "Preliminaries: From Neurons to Neural Networks",
            "Training a neural network",
            "Practical Machine Learning",
            "TensorFlow, exercises, practice, and what to learn next",
            "Project: Facial Expression Recognition",
            "Backpropagation Supplementary Lectures",
            "Higher-level Discussion",
        ]
    },
    {
        id: "oETsMx",
        category: "inlay",
        image: course_images.data_science_4,
        course_name: "R Programming A-Z™: R For Data Science With Real Exercises!",
        description: "Learn Programming In R And R Studio. Data Analytics, Data Science, Statistical Analysis, Packages, Functions, GGPlot2",
        rating_count: 47264,
        rating_star: 4.8,
        students: 237914,
        creator: "Kirill Eremenko, Ligency Team",
        updated_date: "11/2021",
        lang: "english",
        actual_price: 45.99,
        discounted_price: 6.99,
        what_you_will_learn: [
            "Learn to program in R at a good level",
            "Learn the core principles of programming",
            "Learn how to create variables",
            "Learn how to create a while() loop and a for() loop in R",
            "Learn the matrix() function, learn rbind() and cbind()",
            "Learn how to customize R studio to suit your preferences"
        ],
        content: [
            "Hit The Ground Running",
            "Core Programming Principles",
            "Fundamentals of R",
            "Matrices",
            "Data Frames",
            "Advanced Visualization with GGPlot2",
            "Homework Solutions",
        ]
    },
    {
        id: "-aWjaj",
        category: "inlay",
        image: course_images.data_science_5,
        course_name: "Data Science and Machine Learning Bootcamp with R",
        description: "Learn how to use the R programming language for data science and machine learning and data visualization!",
        rating_count: 32103,
        rating_star: 5,
        students: 204985,
        creator: "Jose Portilla",
        updated_date: "12/2020",
        lang: ["english", "arabic"],
        actual_price: 77.99,
        discounted_price: 16.99,
        what_you_will_learn: [
            "Program in R",
            "Create Data Visualizations",
            "Use R to manipulate data easily",
            "Use R for Data Science",
            "Use R for Data Analysis",
            "Use R to handle csv,excel,SQL files or web scraping",
            "Use R for Machine Learning Algorithms"
        ],
        content: [
            "Course Best Practices",
            "Windows Installation Set-Up",
            "Mac OS Installation Set-Up",
            "Linux Installation",
            "Development Environment Overview",
            "Introduction to R Basics",
            "R Data Frames",
        ]
    },
    {
        id: "xxxbMD",
        category: "engraved_copper",
        image: course_images.aws_1,
        course_name: "Amazon Web Services (AWS) Certified 2022 - 4 Certifications!",
        description: "Videos, labs & practice exams - AWS Certified (Solutions Architect, Developer, SysOps Administrator, Cloud Practitioner)",
        rating_count: 21046,
        rating_star: 4.2,
        students: 134932,
        creator: "BackSpace Academy, Paul Coady",
        updated_date: "12/2021",
        lang: ["english", "arabic"],
        actual_price: 69.99,
        discounted_price: 11.99,
        what_you_will_learn: [
            "You will be fully prepared for the",
            "AWS Certified Solutions Architect",
            "Associate, AWS Certified Developer",
            "Associate and AWS Certified SysOps ...",
        ],
        content: [
            "AWS Cerified Cloud Practitioner",
            "AWS Certified Associate Core Knowledge",
            "AWS Certified Developer Associate - Final Preparation",
            "AWS Certified Solutions Architect Associate - Final Preparation",
            "AWS Certified SysOps Administrator Associate - Final Preparation",
        ]
    },
    {
        id: "cIdBd2",
        category: "engraved_copper",
        image: course_images.aws_2,
        course_name: "AWS Certified Security Specialty 2022",
        description: "All you need to master AWS Certified Security Specialty certification.",
        rating_count: 5387,
        rating_star: 4.5,
        students: 33385,
        creator: "Zeal Vora",
        updated_date: "12/2022",
        lang: ["english", "french"],
        actual_price: 34.99,
        discounted_price: 10.99,
        what_you_will_learn: [
            "Will be prepared to give AWS Certified Security Specialty Exam",
            "Gain deep insights about Enterprise grade Security implementation.",
            "You will be able to Master the Security aspect of AWS",
            "Will be able to detect attacks and protect the AWS infrastructure from Hackers.",
        ],
        content: [
            "Getting started with the course",
            "Domain 1 - Incident Response",
            "Domain 2 - Logging & Monitoring",
            "Domain 3 - Infrastructure Security",
            "Domain 4 - Identity & Access Management",
            "Domain 5 - Data Protection"
        ]
    },
    {
        id: "NkZeqm",
        category: "engraved_copper",
        image: course_images.aws_3,
        course_name: "Part 1: AWS Certified Solutions Architect SAA C03 [Updated]",
        description: "AWS Associate Exam - Master Foundations. Join Live Study Group Q&A!",
        rating_count: 1603,
        rating_star: 4.5,
        students: 10933,
        creator: "Chandra Lingam",
        updated_date: "8/2022",
        lang: "english",
        actual_price: 71.99,
        discounted_price: 15.99,
        what_you_will_learn: [
            "Breadth of understanding of various AWS services",
            "How to Integrate Services into a Complete Solution",
            "Hands-on Scenario Based Learning",
            "Weekly Study Group Discussion Sessions",
            "Concise and Precise Preparation for AWS Solutions Architect Certification"
        ],
        content: [
            "Housekeeping",
            "Infrastructure, Pricing, Support - Review",
            "Networking Primer",
            "Virtual Private Cloud (VPC) - Networking Infrastructure",
            "Elastic Compute Cloud (EC2) - Compute Service",
            "Monitoring Resource in Cloud"
        ]
    },
    {
        id: "NkZeqq",
        category: "sand",
        image: course_images.design_2,
        course_name: "Photoshop Master Course: From Beginner to Photoshop Pro",
        description: "This Adobe Photoshop Beginner Course will teach a Beginner Photoshop user all essentials of Adobe Photoshop CC",
        rating_count: 5066,
        rating_star: 4.9,
        students: 143812,
        creator: "Manfred Werner",
        updated_date: "7/2020",
        lang: ["english", "spanish"],
        actual_price: 13.99,
        discounted_price: 5.99,
        what_you_will_learn: [
            "What Photoshop is & how to get into it!",
            "Customize the programs layout & feel comfortable",
            "Understand layers & it's panels",
            "Understand adjustment layers how to use them",
            "Understand setting color profiles, save PSD files & web files",
            "Understand cutting objects out, fixing skin & manipulation"
        ],
        content: [
            "Photoshop Interface & Workspace - For Beginners",
            "Important Photoshop Tools - For Beginners",
            "Retouching Class - Photoshop Portrait Retouching Course",
            "Retouching Class 2 - Photoshop Portrait Retouching Course",
            "Retouching Class 3 - The Instagramer",
            "Bonus Lectures"
        ]
    },
    {
        id: "bLZepe",
        category: "sand",
        image: course_images.design_1,
        course_name: "User Experience (UX): The Ultimate Guide to Usability and UX",
        description: "Get a job in UX and build your user research and UX design skills with this hands-on user experience training course.",
        rating_count: 6250,
        rating_star: 4.4,
        students: 22090,
        creator: "David Travis",
        updated_date: "4/2020",
        lang: ["english", "italian"],
        actual_price: 79.99,
        discounted_price: 16.99,
        what_you_will_learn: [
            "Bake UX into your workflow by following a proven, user centred design framework.",
            "Moderate a usability test and prioritise the observations.",
            "Uncover and describe users’ mental models.",
            "Design and conduct online and offline card sorting sessions.",
            "Develop cheap, throwaway prototypes to get quick and frequent feedback from your users."
        ],
        content: [
            "Going where the action is: Understading users in context",
            "How to get niche quick",
            "UX Design Activities - Build your UX Portfolio",
            "What can a London bus teach us about usability?",
            "Beyong 'easy to use': Measuring the user experience",
            "Site structure and navigation: Finding is the new doing",
            "Interaction design: Simple rules for designing simple screens"
        ]
    },
    {
        id: "RkZecd",
        category: "spray",
        image: course_images.marketing_1,
        course_name: "Copywriting - Become a Freelance Copywriter, your own boss",
        description: "Build a successful freelance copywriting business - turn basic writing skills into a paycheck.",
        rating_count: 2779,
        rating_star: 4.8,
        students: 32657,
        creator: "Len Smith, Sean Kaye",
        updated_date: "4/2018",
        lang: "english",
        actual_price: 88.99,
        discounted_price: 16.99,
        what_you_will_learn: [
            "Part one – everything you need for a fast-track start, including your first article",
            "Part three – the essential skills that mark out a real pro",
            "Part two – the copywriter’s ‘how to’: sales copy, expert copy, and more!",
            "Part four – how to boost your income and turn your new website into a money magnet",
        ],
        content: [
            "Choose projects whre you feel comfortable",
            "Back to basics II",
            "How to boost your copywriting income",
            "More on pricing your work",
            "This and that",
            "Conclusion"
        ]
    },
    {
        id: "NrZ_qd",
        category: "spray",
        image: course_images.marketing_2,
        course_name: "How to Market Yourself as a Coach or Consultant",
        description: "Learn a Proven, Step-by-Step Process You Can Use to Package, Brand, Market, & Sell Your Coaching or Consulting Services",
        rating_count: 963,
        rating_star: 3.8,
        students: 11848,
        creator: "Debbie LaChusa",
        updated_date: "4/2022",
        lang: "english",
        actual_price: 40.99,
        discounted_price: 10.99,
        what_you_will_learn: [
            "Identify who your Ideal Clients are so you know exactly who to market and sell to",
            "Learn how to create a Signature Program so you can stop selling your time or creating spec proposals",
            "Learn how to write Compelling Marketing Copy you can use to attract your ideal clients",
            "Learn how to create a Financially Viable Business and understand exactly what it will take to reach your financial goals",
            "Learn how to easily create your own Wordpress Coaching or Consulting Website"
        ],
        content: [
            "Building Your Business & Marketing Foundation",
            "Packaging Your Services",
            "Branding Yourself & Your Business",
            "Marketing Message Development",
            "Getting clients: Objectives & strategies",
            "Markting Yourself Online: Website Development",
            "Marketing Implementation: Create a 90-Day Marketing Plan",
        ]
    },
];

export default courses;